# This file is part of home-mqtt-url-relay.
# https://github.com/garaemon/home-mqtt-url-relay

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2017, garaemon <garaemon@gmail.com>

language: python

python:
    - "3.4"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
